# Exit Zero school check. Do not edit this file.

import os
import sys

# e0 runs checks from the repository root.
sys.path.insert(0, os.getcwd())


def test_farewell_returns_expected_string():
    import greeting

    assert greeting.farewell("Ada") == "Goodbye, Ada!"
