# Exit Zero school check. Do not edit this file.
# Your local copy is only for running tests while you work; CI uses the original.

import os
import sys

# e0 runs checks from the repository root.
sys.path.insert(0, os.getcwd())


def test_greet_returns_expected_string():
    import greeting

    assert greeting.greet("Ada") == "Hello, Ada!"
